apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: shandroid19/interact-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: ${BACKEND_URL}
        - name: CHAT_URL
          value: ${CHAT_URL}

---


apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30100
